Repository lucky-treee/Shop_Service, pull requests merged in 2023-01, with the labels that each got.

#16 [FEAT] 응답객체 구현
  src/main/java/com/luckytree/shop_service/ResultResponse.java
Labels: enhancement

#23 [issue#11] API 명세를 확인하기 위하여 Swagger 구현
  build.gradle.kts
  src/main/java/com/luckytree/shop_service/SwaggerConfig.java
  src/main/resources/application.properties
Labels: enhancement

#24 feature/#8 [샵 등록 신청 API 구현]
  build.gradle.kts
  src/main/java/com/luckytree/shop_service/adapter/in/CreateShopController.java
  src/main/java/com/luckytree/shop_service/adapter/out/BaseTimeEntity.java
  src/main/java/com/luckytree/shop_service/adapter/out/CreateShopPersistenceAdapter.java
  src/main/java/com/luckytree/shop_service/adapter/out/ShopDetailEntity.java
  src/main/java/com/luckytree/shop_service/adapter/out/ShopDetailRepository.java
  src/main/java/com/luckytree/shop_service/adapter/out/ShopListEntity.java
  src/main/java/com/luckytree/shop_service/adapter/out/ShopListRepository.java
  src/main/java/com/luckytree/shop_service/application/port/in/CreateShopUseCase.java
  src/main/java/com/luckytree/shop_service/application/port/in/RequestShopRegistration.java
  src/main/java/com/luckytree/shop_service/application/port/out/CreateShopPort.java
  src/main/java/com/luckytree/shop_service/application/service/CreateShopService.java
  src/main/java/com/luckytree/shop_service/domain/Hashtag.java
  src/main/java/com/luckytree/shop_service/domain/ShopDetail.java
  src/main/java/com/luckytree/shop_service/domain/ShopDetailAlteration.java
  src/main/java/com/luckytree/shop_service/domain/ShopList.java
  src/main/java/com/luckytree/shop_service/domain/ShopStatus.java
Labels: question

#27 feature/#26 [엔티티 리팩토링]
  build/classes/java/main/com/luckytree/shop_service/shop/adapter/out/persistence/ShopDetailEntity$ShopDetailEntityBuilder.class
  build/classes/java/main/com/luckytree/shop_service/shop/adapter/out/persistence/ShopDetailEntity.class
  build/classes/java/main/com/luckytree/shop_service/shop/adapter/out/persistence/ShopListEntity$ShopListEntityBuilder.class
  build/classes/java/main/com/luckytree/shop_service/shop/adapter/out/persistence/ShopListEntity.class
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/CreateShopPersistenceAdapter.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/ShopDetailEntity.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/ShopListEntity.java
  src/main/java/com/luckytree/shop_service/shop/application/port/out/CreateShopPort.java
  src/main/java/com/luckytree/shop_service/shop/application/service/CreateShopService.java
  src/main/java/com/luckytree/shop_service/shop/domain/ShopDetail.java
  src/main/java/com/luckytree/shop_service/shop/domain/ShopList.java
Labels: enhancement

#29 feature/#19 [logback & slack]
  build.gradle.kts
  build/resources/main/application.yml
  src/main/resources/application.yml
  src/main/resources/logback-develop.xml
  src/main/resources/logback-product.xml
Labels: enhancement

#30 feature/#21 [에러 핸들러 구현]
  src/main/java/com/luckytree/shop_service/common/dto/ResultResponse.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/ControllerAdvice.java
Labels: enhancement

#31 feature/#1 config repository 의 develop 브랜치를 보도록 수정
  src/main/resources/application.yml
Labels: good first issue

#45 feature/#44 [위도 경도 컬럼명 변경]
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/ShopEntity.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/ShopTempEntity.java
  src/main/java/com/luckytree/shop_service/shop/application/port/in/ShopRequest.java
  src/main/java/com/luckytree/shop_service/shop/domain/ShopSummary.java
Labels: 🛠️ Refactor

#46 feature/#9 [샵 전체조회에 범위를 추가]
  src/main/java/com/luckytree/shop_service/shop/adapter/in/web/GetShopListController.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/GetShopListPersistenceAdapter.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/ShopRepository.java
  src/main/java/com/luckytree/shop_service/shop/application/port/in/GetShopListUseCase.java
  src/main/java/com/luckytree/shop_service/shop/application/port/out/GetShopPort.java
  src/main/java/com/luckytree/shop_service/shop/application/service/GetShopListService.java
Labels: 🐞 Fix

#47 feature/#12 [특정 해시태그에 해당하는 샵의 요약정보 조회]
  src/main/java/com/luckytree/shop_service/shop/adapter/in/web/GetShopListController.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/GetShopListPersistenceAdapter.java
  src/main/java/com/luckytree/shop_service/shop/adapter/out/persistence/ShopRepository.java
  src/main/java/com/luckytree/shop_service/shop/application/port/in/GetShopListUseCase.java
  src/main/java/com/luckytree/shop_service/shop/application/port/out/GetShopPort.java
  src/main/java/com/luckytree/shop_service/shop/application/service/GetShopListService.java
Labels: ➕ Feature
